import Badge from '../models/badgeModel.js';

const initialBadges = [
  // === ONBOARDING BADGES (5 badges) ===
  {
    name: 'Welcome Aboard',
    description: 'Create your account and complete your basic student profile details.',
    icon: 'onboarding_welcome',
    rarity: 'Common',
    category: 'Onboarding',
    criteria: { type: 'profile_complete', value: 1 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'First Steps',
    description: 'Enroll in your very first course on Jagat Academy.',
    icon: 'onboarding_course_1',
    rarity: 'Common',
    category: 'Onboarding',
    criteria: { type: 'course_count', value: 1 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Ice Breaker',
    description: 'Submit your first course lecture completion progress.',
    icon: 'onboarding_watch_1',
    rarity: 'Common',
    category: 'Onboarding',
    criteria: { type: 'watch_time', value: 0.01 }, // just watch a bit
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Seeker of Knowledge',
    description: 'Enroll in at least 3 courses to build a custom multi-topic learning schedule.',
    icon: 'onboarding_course_3',
    rarity: 'Rare',
    category: 'Onboarding',
    criteria: { type: 'course_count', value: 3 },
    xpReward: 150,
    coinsReward: 75,
  },
  {
    name: 'Library Master',
    description: 'Enroll in 5+ courses to broaden your academic foundations.',
    icon: 'onboarding_course_5',
    rarity: 'Epic',
    category: 'Onboarding',
    criteria: { type: 'course_count', value: 5 },
    xpReward: 300,
    coinsReward: 150,
  },

  // === CONSISTENCY BADGES (12 badges) ===
  {
    name: 'First Spark',
    description: 'Maintain a learning streak of 3 consecutive active days.',
    icon: 'consistency_streak_3',
    rarity: 'Common',
    category: 'Consistency',
    criteria: { type: 'streak', value: 3 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Week One Done',
    description: 'Maintain a daily learning streak of 7 consecutive active days.',
    icon: 'consistency_streak_7',
    rarity: 'Common',
    category: 'Consistency',
    criteria: { type: 'streak', value: 7 },
    xpReward: 100,
    coinsReward: 50,
  },
  {
    name: 'Halfway Streak',
    description: 'Maintain a learning streak of 15 consecutive active days.',
    icon: 'consistency_streak_15',
    rarity: 'Rare',
    category: 'Consistency',
    criteria: { type: 'streak', value: 15 },
    xpReward: 150,
    coinsReward: 75,
  },
  {
    name: 'Month of Fire',
    description: 'Maintain a learning streak of 30 consecutive active days. Elite habit build!',
    icon: 'consistency_streak_30',
    rarity: 'Epic',
    category: 'Consistency',
    criteria: { type: 'streak', value: 30 },
    xpReward: 300,
    coinsReward: 150,
  },
  {
    name: 'Streak Legend',
    description: 'Maintain a massive learning streak of 90 consecutive active days!',
    icon: 'consistency_streak_90',
    rarity: 'Legendary',
    category: 'Consistency',
    criteria: { type: 'streak', value: 90 },
    xpReward: 1000,
    coinsReward: 500,
  },
  {
    name: 'Centurion Streak',
    description: 'Achieve a 100-day active learning streak. Absolutely mind-blowing.',
    icon: 'consistency_streak_100',
    rarity: 'Legendary',
    category: 'Consistency',
    criteria: { type: 'streak', value: 100 },
    xpReward: 1500,
    coinsReward: 750,
  },
  {
    name: 'Punctual Learner',
    description: 'Watch video content for 1 hour to establish your core study routine.',
    icon: 'consistency_watch_1h',
    rarity: 'Common',
    category: 'Consistency',
    criteria: { type: 'watch_time', value: 1 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Dedicated Student',
    description: 'Watch lectures for 5 hours. Your learning efforts are growing!',
    icon: 'consistency_watch_5h',
    rarity: 'Common',
    category: 'Consistency',
    criteria: { type: 'watch_time', value: 5 },
    xpReward: 100,
    coinsReward: 50,
  },
  {
    name: 'Academic Grinder',
    description: 'Log 20 hours watching course content and lectures.',
    icon: 'consistency_watch_20h',
    rarity: 'Rare',
    category: 'Consistency',
    criteria: { type: 'watch_time', value: 20 },
    xpReward: 200,
    coinsReward: 100,
  },
  {
    name: 'Deep Focus',
    description: 'Log 50 hours of total active video learning on the platform.',
    icon: 'consistency_watch_50h',
    rarity: 'Epic',
    category: 'Consistency',
    criteria: { type: 'watch_time', value: 50 },
    xpReward: 400,
    coinsReward: 200,
  },
  {
    name: 'Mastery Hours',
    description: 'Amass 100+ hours of watched lectures. Unstoppable dedication!',
    icon: 'consistency_watch_100h',
    rarity: 'Legendary',
    category: 'Consistency',
    criteria: { type: 'watch_time', value: 100 },
    xpReward: 1000,
    coinsReward: 500,
  },
  {
    name: 'Titan of Intellect',
    description: 'Amass 200+ hours of video learning progress. Truly supreme learning.',
    icon: 'consistency_watch_200h',
    rarity: 'Legendary',
    category: 'Consistency',
    criteria: { type: 'watch_time', value: 200 },
    xpReward: 2000,
    coinsReward: 1000,
  },

  // === PERFORMANCE BADGES (12 badges) ===
  {
    name: 'First Agrade',
    description: 'Unlock your first A grade on any evaluated class assignment.',
    icon: 'performance_grade_a',
    rarity: 'Common',
    category: 'Performance',
    criteria: { type: 'quiz_perfect', value: 1 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Triple Crown Grade',
    description: 'Perform flawlessly to secure 3 perfect marks on quizzes or assignments.',
    icon: 'performance_perfect_3',
    rarity: 'Rare',
    category: 'Performance',
    criteria: { type: 'quiz_perfect', value: 3 },
    xpReward: 200,
    coinsReward: 100,
  },
  {
    name: 'Academic Paragon',
    description: 'Score 5 perfect marks across your curriculum.',
    icon: 'performance_perfect_5',
    rarity: 'Epic',
    category: 'Performance',
    criteria: { type: 'quiz_perfect', value: 5 },
    xpReward: 400,
    coinsReward: 200,
  },
  {
    name: 'Level 5 Unlocked',
    description: 'Increase your expertise to reach level 5.',
    icon: 'performance_level_5',
    rarity: 'Common',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 5 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Level 10 Achieved',
    description: 'Reach level 10 and unlock custom card cosmetics.',
    icon: 'performance_level_10',
    rarity: 'Common',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 10 },
    xpReward: 100,
    coinsReward: 50,
  },
  {
    name: 'Level 20 Elite',
    description: 'Reach level 20 to unlock custom profile borders.',
    icon: 'performance_level_20',
    rarity: 'Rare',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 20 },
    xpReward: 200,
    coinsReward: 100,
  },
  {
    name: 'Level 30 Sage',
    description: 'Reach level 30 to unlock retro themes and rewards.',
    icon: 'performance_level_30',
    rarity: 'Epic',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 30 },
    xpReward: 400,
    coinsReward: 200,
  },
  {
    name: 'Level 50 Titan',
    description: 'Reach level 50! A grand pillar of the Jagat Academy community.',
    icon: 'performance_level_50',
    rarity: 'Legendary',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 50 },
    xpReward: 800,
    coinsReward: 400,
  },
  {
    name: 'Level 75 Oracle',
    description: 'Ascend to level 75, unlocking top tier reputation unlocks.',
    icon: 'performance_level_75',
    rarity: 'Legendary',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 75 },
    xpReward: 1200,
    coinsReward: 600,
  },
  {
    name: 'Level 100 Supreme',
    description: 'Conquer the leveling hierarchy to reach level 100! Ready to prestige.',
    icon: 'performance_level_100',
    rarity: 'Legendary',
    category: 'Performance',
    criteria: { type: 'level_milestone', value: 100 },
    xpReward: 2000,
    coinsReward: 1000,
  },
  {
    name: 'Speed Demon',
    description: 'Complete any quiz or module test with perfect marks on the double.',
    icon: 'performance_speed',
    rarity: 'Rare',
    category: 'Performance',
    criteria: { type: 'quiz_perfect', value: 2 },
    xpReward: 150,
    coinsReward: 75,
  },
  {
    name: 'Supreme Grandmaster',
    description: 'Get 10 perfect quiz marks. Pure academic flawlessness.',
    icon: 'performance_perfect_10',
    rarity: 'Legendary',
    category: 'Performance',
    criteria: { type: 'quiz_perfect', value: 10 },
    xpReward: 1500,
    coinsReward: 750,
  },

  // === SOCIAL BADGES (11 badges) ===
  {
    name: 'Icebreaker Answer',
    description: 'Answer 1 student doubt to start helping peers in the course forums.',
    icon: 'social_doubt_1',
    rarity: 'Common',
    category: 'Social',
    criteria: { type: 'doubts_solved', value: 1 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Good Samaritan',
    description: 'Answer 5 student doubts to help resolve peer learning bottlenecks.',
    icon: 'social_doubt_5',
    rarity: 'Common',
    category: 'Social',
    criteria: { type: 'doubts_solved', value: 5 },
    xpReward: 100,
    coinsReward: 50,
  },
  {
    name: 'Active Helper',
    description: 'Successfully resolve 10 student doubts. Community hero!',
    icon: 'social_doubt_10',
    rarity: 'Rare',
    category: 'Social',
    criteria: { type: 'doubts_solved', value: 10 },
    xpReward: 200,
    coinsReward: 100,
  },
  {
    name: 'Class Mentor',
    description: 'Help 25 students by resolving doubt threads. Excellence in tutoring!',
    icon: 'social_doubt_25',
    rarity: 'Epic',
    category: 'Social',
    criteria: { type: 'doubts_solved', value: 25 },
    xpReward: 400,
    coinsReward: 200,
  },
  {
    name: 'Legendary Guru',
    description: 'Resolve 50+ student doubts. A grand scholar and teacher of the academy.',
    icon: 'social_doubt_50',
    rarity: 'Legendary',
    category: 'Social',
    criteria: { type: 'doubts_solved', value: 50 },
    xpReward: 1000,
    coinsReward: 500,
  },
  {
    name: 'Generous Heart',
    description: 'Gift 1 of your unlocked badges to a followed friend or learning peer.',
    icon: 'social_gift_1',
    rarity: 'Common',
    category: 'Social',
    criteria: { type: 'gift_badge', value: 1 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Philanthropist',
    description: 'Gift 5 badges to peers to reward their learning achievements.',
    icon: 'social_gift_5',
    rarity: 'Rare',
    category: 'Social',
    criteria: { type: 'gift_badge', value: 5 },
    xpReward: 200,
    coinsReward: 100,
  },
  {
    name: 'Community Pillar',
    description: 'Gift 10 badges to learning peers. Promoting communal success!',
    icon: 'social_gift_10',
    rarity: 'Epic',
    category: 'Social',
    criteria: { type: 'gift_badge', value: 10 },
    xpReward: 400,
    coinsReward: 200,
  },
  {
    name: 'Class Socialite',
    description: 'Follow 5 friends to see their learning and streak achievements.',
    icon: 'social_follow',
    rarity: 'Common',
    category: 'Social',
    criteria: { type: 'gift_badge', value: 0 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Study Syndicate',
    description: 'Be part of a study group working on shared courses.',
    icon: 'social_group',
    rarity: 'Common',
    category: 'Social',
    criteria: { type: 'gift_badge', value: 0 },
    xpReward: 50,
    coinsReward: 25,
  },
  {
    name: 'Global Connector',
    description: 'Amass a network of 20 followers on your public learning profile.',
    icon: 'social_network',
    rarity: 'Rare',
    category: 'Social',
    criteria: { type: 'gift_badge', value: 0 },
    xpReward: 200,
    coinsReward: 100,
  },

  // === MILESTONES BADGES (10 badges) ===
  {
    name: 'Certified Graduate',
    description: 'Earn your first certified course completion credential from Jagat Academy.',
    icon: 'milestone_cert_1',
    rarity: 'Rare',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 1 },
    xpReward: 200,
    coinsReward: 100,
  },
  {
    name: 'Double Diploma',
    description: 'Complete 2 full certified courses.',
    icon: 'milestone_cert_2',
    rarity: 'Rare',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 2 },
    xpReward: 300,
    coinsReward: 150,
  },
  {
    name: 'Multi-Graduate',
    description: 'Complete 5 certified courses. High learning versatility!',
    icon: 'milestone_cert_5',
    rarity: 'Epic',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 5 },
    xpReward: 500,
    coinsReward: 250,
  },
  {
    name: 'LMS Academician',
    description: 'Complete 10 courses on Jagat Academy. Absolute curriculum master!',
    icon: 'milestone_cert_10',
    rarity: 'Legendary',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 10 },
    xpReward: 1500,
    coinsReward: 750,
  },
  {
    name: 'Prestige Tier I',
    description: 'Reset your levels to prestige your profile status for the first time.',
    icon: 'milestone_prestige_1',
    rarity: 'Legendary',
    category: 'Milestones',
    criteria: { type: 'level_milestone', value: 101 },
    xpReward: 2000,
    coinsReward: 1000,
  },
  {
    name: 'Prestige Tier II',
    description: 'Reset levels twice to prestige. A legendary figure in academy lore.',
    icon: 'milestone_prestige_2',
    rarity: 'Legendary',
    category: 'Milestones',
    criteria: { type: 'level_milestone', value: 102 },
    xpReward: 3000,
    coinsReward: 1500,
  },
  {
    name: 'Golden Collector',
    description: 'Amass a total collection of 10 unlocked badges.',
    icon: 'milestone_badge_10',
    rarity: 'Rare',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 1 },
    xpReward: 150,
    coinsReward: 75,
  },
  {
    name: 'Badge Hoarder',
    description: 'Amass 25 unlocked badges. Incredible achievements list!',
    icon: 'milestone_badge_25',
    rarity: 'Epic',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 1 },
    xpReward: 300,
    coinsReward: 150,
  },
  {
    name: 'Trophy Cabinet',
    description: 'Secure 40+ total badges in your showcase drawer.',
    icon: 'milestone_badge_40',
    rarity: 'Legendary',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 1 },
    xpReward: 1000,
    coinsReward: 500,
  },
  {
    name: 'Completionist Lord',
    description: 'Unlock 100% of all available badges in the achievement system. The Ultimate Legend.',
    icon: 'milestone_badge_all',
    rarity: 'Legendary',
    category: 'Milestones',
    criteria: { type: 'course_count', value: 1 },
    xpReward: 5000,
    coinsReward: 2500,
  },
];

export const seedBadges = async () => {
  try {
    console.log('🌱 Seeding & Synchronizing 50 LMS Gamification Badges (SVG IDs) into the database...');
    for (const initialBadge of initialBadges) {
      await Badge.findOneAndUpdate(
        { name: initialBadge.name },
        initialBadge,
        { upsert: true, new: true }
      );
    }
    console.log('✅ Successfully seeded and synchronized 50 badges.');
  } catch (error) {
    console.error('❌ Failed to seed/update badges:', error);
  }
};
